# Generated by Django 5.0.6 on 2024-06-19 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_phase_phase_deadline_task_task_deadline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_manager',
            field=models.CharField(max_length=250),
        ),
    ]
