# Generated by Django 5.0.6 on 2024-06-19 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_remove_project_project_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_start_date',
            field=models.DateTimeField(),
        ),
    ]
