# Generated by Django 5.0.6 on 2024-07-01 11:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_remove_project_author_project_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='id',
            field=models.UUIDField(default=uuid.UUID('29509394-7a32-4892-a31d-52899ca7b7aa'), primary_key=True, serialize=False, unique=True),
        ),
    ]
