# Generated by Django 5.0.6 on 2024-07-01 12:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_alter_documents_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='id',
            field=models.UUIDField(default=uuid.UUID('739e4884-a52c-4c9e-ac8e-9f3b8d18c0aa'), primary_key=True, serialize=False, unique=True),
        ),
    ]
