# Generated by Django 5.0.6 on 2024-07-11 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0021_remove_phase_phase_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='phase',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='projects.phase'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='documents',
            name='phase',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='projects.phase'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='problems',
            name='phase',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='projects.phase'),
            preserve_default=False,
        ),
    ]
