# Generated by Django 5.0.6 on 2024-07-15 12:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0024_alter_phase_id_alter_task_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phase',
            name='id',
            field=models.UUIDField(default=uuid.UUID('edef3ea2-373b-40b9-ae51-89ead447f9b3'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='id',
            field=models.UUIDField(default=uuid.UUID('954d5dca-c830-4bce-b17b-00089d8f0cb7'), primary_key=True, serialize=False),
        ),
    ]
