# Generated by Django 5.0.7 on 2024-08-01 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0033_alter_comments_author_alter_comments_phase_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectfiles',
            name='size',
            field=models.FloatField(default=0),
        ),
    ]
