# Generated by Django 5.0.7 on 2024-08-05 14:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0041_project_project_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyrange',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 8, 5, 14, 7, 40, 5067)),
        ),
    ]
