# Generated by Django 5.0.6 on 2024-06-24 09:12

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 6, 24, 9, 12, 8, 310351, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='expense',
            name='id',
            field=models.UUIDField(default=uuid.UUID('5899b4c6-d339-4acf-91ff-780c11e22c28'), primary_key=True, serialize=False),
        ),
    ]
