# Generated by Django 5.0.7 on 2024-07-22 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_alter_expense_date'),
        ('projects', '0031_remove_problems_status_remove_problems_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='currency',
            field=models.CharField(choices=[('UZS', 'UZS'), ('USD', 'USD')], default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expense',
            name='documents',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='expense',
            name='phase',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='projects.phase'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expense',
            name='task',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='projects.task'),
            preserve_default=False,
        ),
    ]
