# Generated by Django 5.0.7 on 2024-07-22 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0006_alter_expense_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='documents',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='phase',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='task',
        ),
        migrations.AlterField(
            model_name='expense',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
