# Generated by Django 5.0.7 on 2024-07-23 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0007_remove_expense_currency_remove_expense_documents_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='document',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
