# Generated by Django 5.0.6 on 2024-06-28 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0002_alter_action_action'),
        ('projects', '0013_remove_project_author_project_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='project',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='projects.project'),
        ),
    ]
