# Generated by Django 5.0.6 on 2024-07-03 11:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyihalar', '0015_alter_documents_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='id',
            field=models.UUIDField(default=uuid.UUID('da3861c1-90e8-46ad-b1d9-3af500fde091'), primary_key=True, serialize=False, unique=True),
        ),
    ]
