# Generated by Django 5.0.6 on 2024-07-03 16:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyihalar', '0016_alter_documents_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='document',
            field=models.FileField(blank=True, max_length=500, upload_to=''),
        ),
        migrations.AlterField(
            model_name='documents',
            name='id',
            field=models.UUIDField(default=uuid.UUID('91766069-1866-4253-b7c8-58656bbd5999'), primary_key=True, serialize=False),
        ),
    ]
