# Generated by Django 5.0.6 on 2024-07-03 16:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyihalar', '0017_alter_documents_document_alter_documents_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='id',
            field=models.UUIDField(default=uuid.UUID('938c27b0-1f21-4895-b976-a051d72b3fd6'), primary_key=True, serialize=False),
        ),
    ]
