# Generated by Django 5.0.6 on 2024-07-03 16:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyihalar', '0018_alter_documents_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='id',
            field=models.UUIDField(default=uuid.UUID('00d068fe-3fe2-49d8-bdc1-153c9888759b'), primary_key=True, serialize=False, unique=True),
        ),
    ]
