# Generated by Django 5.0.6 on 2024-07-09 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loyihalar', '0020_alter_documents_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phase',
            name='phase_deadline',
        ),
    ]
