# Generated by Django 5.0.6 on 2024-07-12 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyihalar', '0022_comments_phase_documents_phase_problems_phase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='comments',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='problems',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='problems',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
