# Generated by Django 5.0.6 on 2024-07-15 12:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyihalar', '0023_alter_comments_created_at_alter_comments_update_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phase',
            name='id',
            field=models.UUIDField(default=uuid.UUID('af796165-7bd0-4d17-a68c-00b0e24e4227'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='id',
            field=models.UUIDField(default=uuid.UUID('9e93c45d-a729-4de8-90ca-39f0b405a0cd'), primary_key=True, serialize=False),
        ),
    ]
