# Generated by Django 5.0.6 on 2024-07-15 12:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyihalar', '0025_alter_phase_id_alter_task_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phase',
            name='id',
            field=models.UUIDField(default=uuid.UUID('8ced09bc-5799-498b-8ad0-5093bc05d54d'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='id',
            field=models.UUIDField(default=uuid.UUID('3bfff1bb-cf09-4185-8b57-bb3f80f2f425'), primary_key=True, serialize=False),
        ),
    ]
