# Generated by Django 5.0.6 on 2024-07-15 12:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyihalar', '0027_alter_phase_id_alter_task_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phase',
            name='id',
            field=models.UUIDField(default=uuid.UUID('23607cda-8bcd-4f67-a408-a3fc993a9792'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='id',
            field=models.UUIDField(default=uuid.UUID('1c6062c5-49ad-45dc-9ca4-ca1beee081da'), editable=False, primary_key=True, serialize=False),
        ),
    ]
