# Generated by Django 5.0.6 on 2024-07-15 12:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyihalar', '0028_alter_phase_id_alter_task_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phase',
            name='id',
            field=models.UUIDField(default=uuid.UUID('628e11ff-dd46-4144-ac8f-2140b3bcab2b'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='id',
            field=models.UUIDField(default=uuid.UUID('acc00d1c-271c-4fb7-bf39-72466bc7405f'), editable=False, primary_key=True, serialize=False),
        ),
    ]
