# Generated by Django 5.0.6 on 2024-07-15 12:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyihalar', '0029_alter_phase_id_alter_task_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phase',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
