# Generated by Django 4.2.14 on 2024-07-17 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loyihalar', '0030_alter_phase_id_alter_task_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problems',
            name='status',
        ),
        migrations.RemoveField(
            model_name='problems',
            name='title',
        ),
    ]
