# Generated by Django 5.0.7 on 2024-07-31 17:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyihalar', '0031_remove_problems_status_remove_problems_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='phase',
            name='status',
            field=models.CharField(choices=[('Yangi', 'Yangi'), ('Jarayonda', 'Jarayonda'), ('Tugatilgan', 'Tugatilgan')], default='Yangi', max_length=30),
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Yangi', 'Yangi'), ('Jarayonda', 'Jarayonda'), ('Tugatilgan', 'Tugatilgan')], default='Yangi', max_length=150),
        ),
        migrations.AlterField(
            model_name='comments',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comments',
            name='phase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='loyihalar.phase'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='loyihalar.project'),
        ),
        migrations.AlterField(
            model_name='permittedprojects',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='loyihalar.project'),
        ),
        migrations.AlterField(
            model_name='permittedprojects',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='problems',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='problems',
            name='phase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='loyihalar.phase'),
        ),
        migrations.AlterField(
            model_name='problems',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='loyihalar.project'),
        ),
    ]
