# Generated by Django 5.0.7 on 2024-08-01 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loyihalar', '0035_projectfiles_file_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectfiles',
            name='file_name',
        ),
    ]
