# Generated by Django 5.0.7 on 2024-08-01 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyihalar', '0036_remove_projectfiles_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectfiles',
            name='file_name',
            field=models.CharField(default=None, max_length=300),
            preserve_default=False,
        ),
    ]
