# Generated by Django 5.0.7 on 2024-08-01 10:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyihalar', '0037_projectfiles_file_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectfiles',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
