# Generated by Django 5.0.7 on 2024-08-05 12:33

import uuid
from django.db import migrations, models
def set_default_project_number(apps, schema_editor):
    Project = apps.get_model('loyihalar', 'Project')
    for project in Project.objects.all():
        if project.project_number is None:
            project.project_number = 'DEFAULT_NUMBER'
            project.save()

class Migration(migrations.Migration):

    dependencies = [
        ('loyihalar', '0038_alter_projectfiles_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyRange',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.IntegerField(default=1)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='project_number',
            field=models.CharField(max_length=150),
        ),
        migrations.RunPython(set_default_project_number),
    ]
