# Generated by Django 5.0.7 on 2024-08-05 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loyihalar', '0039_dailyrange_project_project_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='project_number',
        ),
    ]
