# Generated by Django 5.0.7 on 2024-08-05 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyihalar', '0040_remove_project_project_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_number',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
